Improve cli, add new command, improve tests
ch-iv/litestar-manage pull request #3
Opened 2024-08-31 23:20 UTC by aarcex3

# Code proposal

The main cli has been refactor and a new command has been added, namely `generate`.
This is a proposal to generate a folder like the ones on the fullstack [example](https://github.com/litestar-org/litestar-fullstack/tree/937d441d920ad5952f2178ec8dfe1f90f5492b5e/src/app/domain), where a resource consists of a controller, service, dtos, models and a repository file.
The proposal is to follow a Nestjs like philosophy when it comes to the cli.

# Related Issue
None

2024-09-10 13:50 UTC, ch-iv requested changes
Hey! Thanks for the pull request, your work is really appreciated. I totally agree with having an option to generate individual resources. In addition to some of the comments that I've left, I also think that you should not use `RenderingContext` for rendering a resource. Instead create another context class (something like `ResourceRenderingContext` with resource specific context fields) and use it to render resources instead.

2024-09-10 13:50 UTC, ch-iv commented on .vscode/settings.json
Remove IDE configuration files from the commit.

2024-09-10 13:50 UTC, ch-iv commented on README.md
> +```bash
Is there a specific reason behind this change?

2024-09-10 13:50 UTC, ch-iv commented on pyproject.toml
> +    "black>=24.8.0",
The project uses ruff for linting. Remove black dependency and lint the PR using ruff.

2024-09-10 13:50 UTC, ch-iv commented on src/litestar_manage/cli.py
> +    pass
This is meant to be an extension of the LItestar's CLI, so it doesn't really make sense for the group to be named CLI. Rename this group back to `project`.

2024-09-10 13:50 UTC, ch-iv commented on src/litestar_manage/cli.py
> -    venv_name = "venv"
We don't want to make assumptions about what the virtual environment name is, nor do we want to hard code that assumption. Factor out the virtual environment name into a constant and possibly make a list of possible venv names to check against.

2024-09-10 18:09 UTC, aarcex3 commented on README.md
> +```bash
It looks cleaner in my opinion, I can remove it if you want

2024-09-10 18:46 UTC, aarcex3 commented
> Hey! Thanks for the pull request, your work is really appreciated. I totally agree with having an option to generate individual resources. In addition to some of the comments that I've left, I also think that you should not use `RenderingContext` for rendering a resource. Instead create another context class (something like `ResourceRenderingContext` with resource specific context fields) and use it to render resources instead.

Would it be ok to make a subclass of RenderingContext for this matter? Or maybe create an abstract RenderingContext from which the other can inherent? Because in most cases we just render jinja files (and others), right?

2024-09-11 23:44 UTC, ch-iv commented
Since `RenderingContext` is a dataclass it wouldn't really make sense to have another class inherit from it. `RenderingContext` just a structure holding some values used during rendering. I would just create another dataclass called `ResourceRenderingContext` without any inheritance. And maybe rename `RenderingContext` to `AppRenderingContext`.

2024-09-17 02:03 UTC, ch-iv commented
@aarcex3 Thank you for your efforts.

2024-09-17 02:03 UTC, merged